spring:
  data:
    mongodb:
      database: javapro
      host: localhost
      port: 27017
      username: root
      password: password
  redis:
    host: localhost
    port: 6379
admin:
  username: admin
  password: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918